### ISSUE TITLE
package_info_plus is not used by the package 

### ISSUE THREAD

**Issue by kodejack** [appupgrade-dev/app_upgrade_flutter_sdk#2]
package_info_plus is not used by the package and is stopping the newer version of the package_info_plus being used in projects

**Comment by appupgrade-dev** [comment]
@kodejack Thanks for raising the issue. We have removed unnecessary package_info_plus and released new version 2.0.2
Please update the version and use the latest one.

**Comment by kodejack** [comment]
Thanks for the swift response and fix.
